plugin bonding_err_: separate misconfiguration warning; exit with error

diff --git a/plugins/node.d.linux/bonding_err_.in b/plugins/node.d.linux/bonding_err_.in
--- a/plugins/node.d.linux/bonding_err_.in
+++ b/plugins/node.d.linux/bonding_err_.in
@@ -74,11 +74,12 @@ if [ "$1" = "suggest" ]; then
   exit 0
 fi
 
+if [ "$MYSELF" = "$FILENAME" ]; then
+    echo "Can't run an un-symlinked plugin. Please run the plugin with 'suggest' before attempting this."
+    exit 1
+fi
+
 if [ "$1" = "config" ]; then
-  if [ "$MYSELF" = "$FILENAME" ]; then
-    echo "Can't run config on un-symlinked plugin. Please run the plugin with 'suggest' before attempting this."
-    exit 0
-  else 
     echo "graph_title Bonding interface errors for $BONDINGIF"
     echo "graph_category Network"
     echo "graph_args --base 1000 -l 0"
@@ -89,13 +90,7 @@ if [ "$1" = "config" ]; then
       echo "if_${fieldname}.min 0"
       echo "if_${fieldname}.warning 0"
     done
-  fi
-  exit 0
-fi
-
-if [ "$MYSELF" = "$FILENAME" ]; then
-  echo "Can't run an un-symlinked plugin. Please run the plugin with 'suggest' before attempting this."
-  exit 0
+    exit 0
 fi
 
 get_bonding_interface_names | while read -r if; do
