Modify node.d.linux/if_ plugin to pull interface speed from sysfs if other methods don't work.

diff --git a/plugins/node.d.linux/if_.in b/plugins/node.d.linux/if_.in
--- a/plugins/node.d.linux/if_.in
+++ b/plugins/node.d.linux/if_.in
@@ -138,6 +138,13 @@ findspeed () {
 	   return;;
     esac
 
+    # sysfs can report the speed if the driver supports it
+    SYSFS="$(cat /sys/class/net/$INTERFACE/speed 2>/dev/null)"
+    # If it can't, it fails on I/O, so we check cat's return value
+    if [ $? -eq 0 -a "$SPEED" = "U" -a -n "$SYSFS" ]; then
+        SPEED="$SYSFS"
+    fi
+
     BPS=$(( $SPEED * 1000 * 1000 ))
 
     cat <<EOF
