use bash syntax for this bash script

diff --git a/plugins/node.d.linux/ip_.in b/plugins/node.d.linux/ip_.in
--- a/plugins/node.d.linux/ip_.in
+++ b/plugins/node.d.linux/ip_.in
@@ -132,11 +132,10 @@ case $IP in
         ;;
 esac
 
-if [ "$1" = "autoconf" ]; then
-        if [ -r /proc/net/dev ]; then
-                iptables -L ${INPUT} -v -n -x >/dev/null 2>/dev/null
-                if [ $? -gt 0 ]; then
-                        echo "no (could not run iptables as user `whoami`)"
+if [[ "$1" == "autoconf" ]]; then
+        if [[ -r /proc/net/dev ]]; then
+                if ! iptables -L ${INPUT} -v -n -x >/dev/null 2>/dev/null; then
+                        echo "no (could not run iptables as user $(whoami))"
                         exit 0
                 else
                         echo yes
@@ -148,19 +147,19 @@ if [ "$1" = "autoconf" ]; then
         fi
 fi
 
-if [ "$1" = "suggest" ]; then
+if [[ "$1" == "suggest" ]]; then
     iptables -L ${INPUT} -v -n -x 2>/dev/null | awk --posix '$8 ~ /^([0-9]{1,3}\.){3}[0-9]{1,3}$/ { if (done[$8]!=1) {print $8; done[$8]=1;}}'
-    if [ -x /sbin/ip6tables ]; then
+    if [[ -x /sbin/ip6tables ]]; then
         ip6tables -L ${INPUT} -v -n -x 2>/dev/null | awk --posix '$7 ~ /\/128$/ { if (done[$7]!=1) {a=$7;gsub(/\/128$/, "", a); print a; done[$7]=1;}}'
     fi
     exit 0
 fi
 
-if [ "$1" = "config" ]; then
+if [[ "$1" == "config" ]]; then
 
         echo "graph_order out in"
         title=$IP
-        if [ -n "$hostname" ]; then
+        if [[ "$hostname" ]]; then
                 title="$hostname"
         fi
         echo "graph_title $title traffic"
@@ -182,10 +181,7 @@ if [ "$1" = "config" ]; then
         exit 0
 fi;
 
-
 # Escape .'s so they don't match _everything_?
-IP="$( echo $IP | sed 's~\.~\\.~g' )"
-
+IP=$(echo $IP | sed 's~\.~\\.~g')
 iptables -L ${INPUT} -v -n -x   | awk "/$IP"'[ /]/ { print "in.value " $2; exit 0; }'
-
 iptables -L ${OUTPUT} -v -n -x  | awk "/$IP"'[ /]/ { print "out.value " $2; exit 0; }'
