fix indentation

diff --git a/plugins/node.d.linux/ip_.in b/plugins/node.d.linux/ip_.in
--- a/plugins/node.d.linux/ip_.in
+++ b/plugins/node.d.linux/ip_.in
@@ -127,24 +127,24 @@ case $IP in
         # This is a fun hack to make the plugin ip6 compatible.
         # Suggested in ticket #439 by "jodal".
         eval 'iptables() {
-                ip6tables "$@"
+            ip6tables "$@"
         }'
         ;;
 esac
 
 if [[ "$1" == "autoconf" ]]; then
-        if [[ -r /proc/net/dev ]]; then
-                if ! iptables -L ${INPUT} -v -n -x >/dev/null 2>/dev/null; then
-                        echo "no (could not run iptables as user $(whoami))"
-                        exit 0
-                else
-                        echo yes
-                        exit 0
-                fi
+    if [[ -r /proc/net/dev ]]; then
+        if ! iptables -L ${INPUT} -v -n -x >/dev/null 2>/dev/null; then
+            echo "no (could not run iptables as user $(whoami))"
+            exit 0
         else
-                echo "no (/proc/net/dev not found)"
-                exit 0
+            echo yes
+            exit 0
         fi
+    else
+        echo "no (/proc/net/dev not found)"
+        exit 0
+    fi
 fi
 
 if [[ "$1" == "suggest" ]]; then
@@ -157,28 +157,28 @@ fi
 
 if [[ "$1" == "config" ]]; then
 
-        echo "graph_order out in"
-        title=$IP
-        if [[ "$hostname" ]]; then
-                title="$hostname"
-        fi
-        echo "graph_title $title traffic"
-        echo 'graph_args --base 1000'
-        echo 'graph_vlabel bits per ${graph_period}'
-        echo 'graph_category network'
-        echo 'out.label sent'
-        echo 'out.type DERIVE'
-        echo 'out.min 0'
-        echo 'out.cdef out,8,*'
-        echo 'in.label received'
-        echo 'in.type DERIVE'
-        echo 'in.min 0'
-        echo 'in.cdef in,8,*'
-        print_warning out
-        print_critical out
-        print_warning in
-        print_critical in
-        exit 0
+    echo "graph_order out in"
+    title=$IP
+    if [[ "$hostname" ]]; then
+        title="$hostname"
+    fi
+    echo "graph_title $title traffic"
+    echo 'graph_args --base 1000'
+    echo 'graph_vlabel bits per ${graph_period}'
+    echo 'graph_category network'
+    echo 'out.label sent'
+    echo 'out.type DERIVE'
+    echo 'out.min 0'
+    echo 'out.cdef out,8,*'
+    echo 'in.label received'
+    echo 'in.type DERIVE'
+    echo 'in.min 0'
+    echo 'in.cdef in,8,*'
+    print_warning out
+    print_critical out
+    print_warning in
+    print_critical in
+    exit 0
 fi;
 
 # Escape .'s so they don't match _everything_?
