plugin netstat: unify the two sets of netstat plugins
There are two families of netstat plugins (by platform):
* cygwin/freebsd/linux/generic: shell script
* aix/sunos: perl script

This changeset reduces the differences between the scripts to a minimum.

diff --git a/plugins/node.d.linux/netstat.in b/plugins/node.d.linux/netstat.in
--- a/plugins/node.d.linux/netstat.in
+++ b/plugins/node.d.linux/netstat.in
@@ -39,74 +39,78 @@ We have never seen that, patch requested.
 
 =cut
 
-. $MUNIN_LIBDIR/plugins/plugin.sh
+. "$MUNIN_LIBDIR/plugins/plugin.sh"
+
+
+NETSTAT_CMD=netstat
+
 
 if [ "$1" = "autoconf" ]; then
-        if ( netstat -s 2>/dev/null >/dev/null ); then
-                echo yes
-                exit 0
-        else
-                if [ $? -eq 127 ]
-                then
-                        echo "no (netstat program not found)"
-                        exit 0
-                else
-                        echo no
-                        exit 0
-                fi
-        fi
+	if ( "$NETSTAT_CMD" -s 2>/dev/null >/dev/null ); then
+		echo yes
+		exit 0
+	else
+		if [ $? -eq 127 ]
+		then
+			echo "no (program $NETSTAT_CMD not found)"
+			exit 0
+		else
+			echo no
+			exit 0
+		fi
+	fi
 fi
 
 if [ "$1" = "config" ]; then
 
-        echo 'graph_title Netstat'
-        echo 'graph_args --base 1000 --logarithmic'
-        echo 'graph_vlabel TCP connections'
-        echo 'graph_category network'
-        echo 'graph_period second'
-        echo 'graph_info This graph shows the TCP activity of all the network interfaces combined.'
-        echo 'active.label active'
-        echo 'active.type DERIVE'
-        echo 'active.max 50000'
-        echo 'active.min 0'
-        echo 'active.info The number of active TCP openings per second.'
-        print_warning active
-        print_critical active
-        echo 'passive.label passive'
-        echo 'passive.type DERIVE'
-        echo 'passive.max 50000'
-        echo 'passive.min 0'
-        echo 'passive.info The number of passive TCP openings per second.'
-        print_warning passive
-        print_critical passive
-        echo 'failed.label failed'
-        echo 'failed.type DERIVE'
-        echo 'failed.max 50000'
-        echo 'failed.min 0'
-        echo 'failed.info The number of failed TCP connection attempts per second.'
-        print_warning failed
-        print_critical failed
-        echo 'resets.label resets'
-        echo 'resets.type DERIVE'
-        echo 'resets.max 50000'
-        echo 'resets.min 0'
-        echo 'resets.info The number of TCP connection resets.'
-        print_warning resets
-        print_critical resets
-        echo 'established.label established'
-        echo 'established.type GAUGE'
-        echo 'established.max 50000'
-        echo 'established.info The number of currently open connections.'
-        print_warning established
-        print_critical established
-        exit 0
+	echo 'graph_title Netstat'
+	echo 'graph_args --base 1000 --logarithmic'
+	echo 'graph_vlabel TCP connections'
+	echo 'graph_category network'
+	echo 'graph_period second'
+	echo 'graph_info This graph shows the TCP activity of all the network interfaces combined.'
+	echo 'active.label active'
+	echo 'active.type DERIVE'
+	echo 'active.min 0'
+	echo 'active.max 50000'
+	echo 'active.info The number of active TCP openings per second.'
+	print_warning active
+	print_critical active
+	echo 'passive.label passive'
+	echo 'passive.type DERIVE'
+	echo 'passive.min 0'
+	echo 'passive.max 50000'
+	echo 'passive.info The number of passive TCP openings per second.'
+	print_warning passive
+	print_critical passive
+	echo 'failed.label failed'
+	echo 'failed.type DERIVE'
+	echo 'failed.min 0'
+	echo 'failed.max 50000'
+	echo 'failed.info The number of failed TCP connection attempts per second.'
+	print_warning failed
+	print_critical failed
+	echo 'resets.label resets'
+	echo 'resets.type DERIVE'
+	echo 'resets.min 0'
+	echo 'resets.max 50000'
+	echo 'resets.info The number of TCP connection resets.'
+	print_warning resets
+	print_critical resets
+	echo 'established.label established'
+	echo 'established.type GAUGE'
+	echo 'established.max 50000'
+	echo 'established.info The number of currently open connections.'
+	print_warning established
+	print_critical established
+	exit 0
 fi
 
 # Newer versions of net tools' netstat have fixed the 'active connection
 # openings' string from plural connections to singular. The match hereby is for
 # both cases.
 #
-netstat -s | awk '
+"$NETSTAT_CMD" -s | awk '
 /active connection(s)? ope/  { print "active.value " $1 }
 /passive connection ope/  { print "passive.value " $1 }
 /failed connection/       { print "failed.value " $1 }
