New version if if_ plugin that also handles mii-tool dependent interfaces and handles absence of tools better. Typo fix in memory plugin.

diff --git a/node/node.d.linux/if_.in b/node/node.d.linux/if_.in
--- a/node/node.d.linux/if_.in
+++ b/node/node.d.linux/if_.in
@@ -1,46 +1,130 @@
-#!/bin/sh
-#
-# Wildcard-plugin to monitor network interfaces. To monitor an
-# interface, link if_<interface> to this file. E.g.
-#
+#!/bin/bash
+
+# Wildcard-plugin to monitor traffic and errors on network
+# interfaces. To monitor an interface, link if_<interface> to this
+# file. E.g.
+
 #    ln -s /usr/share/node/node/plugins-auto/if_ /etc/munin/node.d/if_eth0
-#
+
 # ...will monitor eth0.
-#
+
 # Any device found in /proc/net/dev can be monitored. Examples include
 # ipsec*, eth*, irda* and lo. Please note that aliases cannot be
 # monitored with this plugin.
-#
+
 # Magic markers (optional - used by munin-config and some installation
 # scripts):
-#
+
 #%# family=auto
 #%# capabilities=autoconf suggest
 
+INTERFACE=${0##*if_}
 
-INTERFACE=`basename $0 | sed 's/^if_//g'`
+findspeed () {
 
-if [ "$1" = "autoconf" ]; then
+    # Who whould have thought it's so much work to determine the
+    # maximum speed of a network interface.  Buckle up!
+
+    IWLIST=$(type --path iwlist)
+
+    WIRELESS=0
+    # Do not use interface name to guess technology.  Many many
+    # wifi drivers use "eth*" names.
+    case $IWLIST in
+
+	'')
+            # Used to use iwconfig to look for "no wireless
+            # extentions" message - but this seemed un-needed.  If we
+            # don't have iwlist we can't find out if # the interface
+            # is wireless
+            :;;
+	*)  IWO="$($IWLIST $INTERFACE rate 2>&1)"
+            case $IWO in
+                *no*) :;;
+	        *) WIRELESS=1;;
+	    esac
+	    ;;
+    esac
+
+    SPEED=U
+    # Find speed in Mbps. - or not
+    case $WIRELESS:$IWLIST in
+	0:*)
+	    ETHTOOL=$(type --path ethtool)
+	    if [ -x "$ETHTOOL" ]; then
+		SPEED="$($ETHTOOL $INTERFACE | awk '/Speed:/ { print $2; }')"
+		case $SPEED in
+		    [0-9]*) :;; # OK
+		    *)      SPEED=U;; # Could be "unknown"
+		esac
+	    else
+		INSTALL="ethtool"
+	    fi
+	    ;;
+	1:/*)
+	    # Current bit rate is not very interesting, it varies too often
+	    SPEED=$(echo "$IWO" |
+		    awk 'BEGIN { RATE=U }
+                               { if ($2 == "Mb/s") RATE=$1; } 
+                         END   { print RATE; }')
+
+	    ;;
+	*)
+	    # Wireless interface, cannot find iwlist
+	    INSTALL="wireless-tools"
+	    ;;
+    esac
+
+    MIITOOL=$(type --path mii-tool)
+    case $SPEED:$MIITOOL in
+	U:/*)
+	    SPEED="$($MIITOOL $INTERFACE 2>&1)"
+	    case $SPEED in
+		*1000base*) SPEED=1000;; # as if...
+		*100base*)  SPEED=100;;
+		*10base*)   SPEED=10;;
+		*)          SPEED=U;;
+	    esac
+	    ;;
+    esac
+
+    case $SPEED in
+	U) echo "up.info Traffic of the $INTERFACE interface. Unable to determine interface speed.  Please install ethtool, wireless-tools (or mii-tool), whatever is apropriate for the interface."
+	   return;;
+    esac
+
+    BPS=$(( $SPEED * 1000 * 1000 ))
+
+    cat <<EOF
+up.max $BPS
+up.info Traffic of the $INTERFACE interface. Maximum speed is $SPEED Mbps.
+down.max $BPS
+EOF
+
+    return
+}
+
+
+case $1 in
+    autoconf)
 	if [ -r /proc/net/dev ]; then
-		echo yes
-		exit 0
+	    echo yes
+	    exit 0
 	else
-		echo "no (/proc/net/dev not found)"
-		exit 1
+	    echo "no (/proc/net/dev not found)"
+	    exit 1
 	fi
-fi
-
-if [ "$1" = "suggest" ]; then
+	;;
+    suggest)
 	if [ -r /proc/net/dev ]; then
-		egrep '^ *(eth|wlan|ath|ra)[0-9]+:' /proc/net/dev | cut -f1 -d: | sed 's/ //g'
-		exit 0
+	    egrep '^ *(eth|wlan|ath|ra|sw)[0-9]+:' /proc/net/dev | cut -f1 -d: | sed 's/ //g'
+	    exit 0
 	else
-		exit 1
+	    exit 1
 	fi
-fi
-
-if [ "$1" = "config" ]; then
-
+	;;
+    config)
+		       
 	echo "graph_order down up" 
 	echo "graph_title $INTERFACE traffic"
 	echo 'graph_args --base 1000'
@@ -55,23 +139,19 @@ if [ "$1" = "config" ]; then
 	echo 'up.type COUNTER'
 	echo 'up.negative down'
 	echo 'up.cdef up,8,*'
-	case "$INTERFACE" in
-		ath*|wlan*|ra*)
-			echo -n "up.info Traffic of the $INTERFACE interface. Maximum speed is "
-			which iwlist >/dev/null 2>/dev/null || echo "undeterminable (please install iwlist)."
-			iwlist $INTERFACE rate 2>/dev/null | awk '/Current Bit Rate/ { split ($0, arr, "[=:]"); split (arr[2], arr2, "M"); print (arr2[1]*1000000) " bits per second.\nup.max " (arr2[1]*1000000) "\ndown.max "(arr2[1]*1000000); }'
-			;;
-		*)
-			echo -n "up.info Traffic of the $INTERFACE interface. Maximum speed is "
-			which ethtool >/dev/null 2>/dev/null || echo "undeterminable (please install ethtool)."
-			ethtool $INTERFACE 2>/dev/null | awk '/Speed/ { split ($2, arr2, "M"); print (arr2[1]*1000000) " bits per second.\nup.max " (arr2[1]*1000000) "\ndown.max "(arr2[1]*1000000); }'
-			;;
-	esac
-	exit 0
-fi;
 
-awk -F '[: \t]+' -v interface="$INTERFACE" \
-    '$1 == interface { print "down.value " $2 "\nup.value " $10; exit }
-     $2 == interface { print "down.value " $3 "\nup.value " $11; exit }' \
+	findspeed
+
+	exit 0
+	;;
+esac
+
+# Escape dots in the interface name (eg. vlans) before using it as a regex
+awk -v interface="$INTERFACE" \
+    'BEGIN { gsub(/\./, "\\.", interface) } \
+    $1 ~ "^" interface ":" {
+        split($0, a, /: */); $0 = a[2]; \
+        print "down.value " $1 "\nup.value " $9 \
+    }' \
     /proc/net/dev
 
