Plugin linux/ip_ now does more proper autoconfig/suggest.

diff --git a/node/node.d.linux/ip_.in b/node/node.d.linux/ip_.in
--- a/node/node.d.linux/ip_.in
+++ b/node/node.d.linux/ip_.in
@@ -17,6 +17,9 @@
 # This plugin is based on the if_ plugin.
 #
 #$Log$
+#Revision 1.3  2004/09/10 23:02:22  jimmyo
+#Plugin linux/ip_ now does more proper autoconfig/suggest.
+#
 #Revision 1.2  2004/05/20 13:57:12  jimmyo
 #Set categories to some of the plugins.
 #
@@ -35,8 +38,14 @@ IP=`basename $0 | sed 's/^ip_//g'`
 
 if [ "$1" = "autoconf" ]; then
 	if [ -r /proc/net/dev ]; then
-		echo yes
-		exit 0
+		iptables -L INPUT -v -n -x >/dev/null 2>/dev/null
+		if [ $? -gt 0 ]; then
+			echo "no (could not run iptables as user `whoami`)"
+			exit 1
+		else
+			echo yes
+			exit 0
+		fi
 	else
 		echo "no (/proc/net/dev not found)"
 		exit 1
@@ -44,12 +53,7 @@ if [ "$1" = "autoconf" ]; then
 fi
 
 if [ "$1" = "suggest" ]; then
-	if [ -r /proc/net/dev ]; then
-		ifconfig | grep 'inet addr' | cut -f2 -d: | cut -f1 -d' ' | sed 's/\./\\\./g'
-		exit 0
-	else
-		exit 1
-	fi
+	iptables -L INPUT -v -n -x 2>/dev/null | awk '$8 ~ /[0-9]/ { if (done[$8]!=1) {print $8; done[$8]=1;}}'
 fi
 
 if [ "$1" = "config" ]; then
