Merge in Tore's changes in branches/debian/etch/dists/debian. The other changes in branches/debian/etch come next.

diff --git a/dists/debian/munin-node.init b/dists/debian/munin-node.init
--- a/dists/debian/munin-node.init
+++ b/dists/debian/munin-node.init
@@ -1,97 +1,192 @@
-#! /bin/sh
+#! /bin/bash
 
 PATH=/sbin:/bin:/usr/sbin:/usr/bin
 DAEMON=/usr/sbin/munin-node
-NAME=munin-node
 PIDFILE=/var/run/munin/munin-node.pid
+CONFFILE=/etc/munin/munin-node.conf
 
-test -f $DAEMON || exit 0
+# log_daemon_msg() and log_progress_msg() isn't present in present in Sarge.
+# Below is a copy of them from lsb-base 3.0-5, for the convenience of back-
+# porters.  If the installed version of lsb-base provides these functions,
+# they will be used instead.
 
-set -e
+log_daemon_msg () {
+    if [ -z "$1" ]; then
+        return 1
+    fi
 
-is_running() {
-	if [ -e $PIDFILE ]; then
-		if kill -0 $(cat $PIDFILE) &>/dev/null; then
-			return 0
-		fi
-	elif pgrep -f "^$DAEMON\$" >/dev/null; then
-		return 0
-	fi
-	return 1
+    if [ -z "$2" ]; then
+        echo -n "$1:"
+        return
+    fi
+    
+    echo -n "$1: $2"
 }
 
-stop() {
-	echo -n "Stopping munin-node: "
-	if ! is_running; then
-		echo "not running."
-		return 0
+log_progress_msg () {
+    if [ -z "$1" ]; then
+        return 1
+    fi
+    echo -n " $@"
+}
+
+. /lib/lsb/init-functions
+
+if [ ! -x $DAEMON ]; then
+	log_failure_msg "Munin-Node appears to be uninstalled."
+	exit 5
+elif [ ! -e $CONFFILE ]; then
+	log_failure_msg "Munin-Node appears to be unconfigured."
+	exit 6
+fi
+
+# Figure out if the pid file is in a non-standard location
+while read line; do
+	line=${line%%\#*} # get rid of comments
+	set -f
+	line=$(echo $line) # get rid of extraneous blanks
+	set +f
+	if [ "$line" != "${line#pid_file }" ]; then
+		PIDFILE=${line#pid_file }
 	fi
-	start-stop-daemon --stop --oknodo --pidfile $PIDFILE
-	sleep 1
-	if is_running; then
-		echo -n "waiting.."
-		if ! (sleep 2; is_running); then
-			echo "done."
-			return 0
-		fi
-		echo -n "failed, trying with signals.."
-		pkill -15 -f "^$DAEMON\$"
-		echo -n "SIGTERM.."
-		sleep 1
-		if ! is_running; then
-			echo "done."
-			return 0
-		fi
-		WAIT=5
-		echo -n "SIGKILL.."
-		pkill -9 -f "^$DAEMON\$"
-		while [ $WAIT -ge 0 ] && sleep 1; do
-			if ! is_running; then
-				echo "done."
-				return 0
-			fi
-			WAIT=$(( WAIT - 1 ))
-			echo -n "."
-		done
-		echo "FAILED!"
-		exit 1
-	fi
-	echo "done."
+done < $CONFFILE
+
+verify_superuser() {
+	action=$1
+	# dash/ash do not provide $EUID, set it explicitly if not
+	# I can't find any way of avoiding a fork in these
+	# shells - drop me an email if you've got any suggestions
+	[ -z "$EUID" ] && EUID=$(id -u)
+	[ $EUID -eq 0 ] && return
+	log_failure_msg "Superuser privileges required for the" \
+			"\"$action\" action."
+	exit 4
 }
 
 start() {
-	echo -n "Starting munin-node: "
-	if is_running; then
-		echo "already running."
+	log_daemon_msg "Starting Munin-Node"
+	if pidofproc -p $PIDFILE $DAEMON >/dev/null; then
+		log_progress_msg "started beforehand"
+		log_end_msg 0
 		exit 0
 	fi
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON
-	if is_running; then
-		echo "done."
-		return 0
-	fi
-	if ! (sleep 2; is_running); then
-		echo "FAILED!"
-		exit 1
-	fi
+	start_daemon -p $PIDFILE $DAEMON
+	ret=$?
+	# start_daemon() isn't thorough enough, ensure the daemon has been
+	# started manually
+	attempts=0
+	until pidofproc -p $PIDFILE $DAEMON >/dev/null; do
+		attempts=$(( $attempts + 1 ))
+		sleep 0.05
+		[ $attempts -lt 20 ] && continue
+		log_end_msg 1
+		return 1
+	done
+	[ $ret -eq 0 ] && log_progress_msg "done"
+	log_end_msg $ret
+	return $ret
 }
-	
+
+stop() {
+	log_daemon_msg "Stopping Munin-Node"
+	# killproc() doesn't try hard enough if the pid file is missing,
+	# so create it is gone and the daemon is still running
+	if [ ! -r $PIDFILE ]; then
+		pid=$(pidofproc -p $PIDFILE $DAEMON)
+		if [ -z "$pid" ]; then
+			log_progress_msg "stopped beforehand"
+			log_end_msg 0
+			return 0
+		fi
+		echo $pid 2>/dev/null > $PIDFILE
+		if [ $? -ne 0 ]; then
+			log_end_msg 1
+			return 1
+		fi
+	fi
+	# This may look strange, but because start-stop-daemon looks at
+	# /proc/pid/exe I need to specify /usr/bin/perl as the "daemon"
+	killproc -p $PIDFILE /usr/bin/perl
+	ret=$?
+	# killproc() isn't thorough enough, ensure the daemon has been
+	# stopped manually
+	attempts=0
+	until ! pidofproc -p $PIDFILE $DAEMON >/dev/null; do
+		attempts=$(( $attempts + 1 ))
+		sleep 0.05
+		[ $attempts -lt 20 ] && continue
+		log_end_msg 1
+		return 1
+	done
+	[ $ret -eq 0 ] && log_progress_msg "done"
+	log_end_msg $ret
+	return $ret
+}
+
+if [ "$#" -ne 1 ]; then
+	log_failure_msg "Usage: /etc/init.d/munin-node" \
+			"{start|stop|restart|force-reload|try-restart}"
+	exit 2
+fi
+
 case "$1" in
   start)
+  	verify_superuser $1
   	start
+	exit $?
 	;;
   stop)
+  	verify_superuser $1
   	stop
+	exit $?
 	;;
   restart|force-reload)
-  	stop
+  	verify_superuser $1
+  	stop || exit $?
 	start
+	exit $?
 	;;
+  try-restart)
+  	verify_superuser $1
+	pidofproc -p $PIDFILE $DAEMON >/dev/null
+	if [ $? -eq 0 ]; then
+		stop || exit $?
+		start
+		exit $?
+	fi
+	log_success_msg "Munin-Node was stopped beforehand and thus not" \
+			"restarted."
+	exit 0
+	;;
+  reload)
+  	log_failure_msg "The \"reload\" action is not implemented."
+	exit 3
+	;;
+  status)
+  	pid=$(pidofproc -p $PIDFILE $DAEMON)
+	ret=$?
+	pid=${pid% } # pidofproc() supplies a trailing space, strip it
+	if [ $ret -eq 0 ]; then
+		log_success_msg "Munin-Node is running (PID: $pid)"
+		exit 0
+	# the LSB specifies that I in this case (daemon dead + pid file exist)
+	# should return 1, so why init-functions use 2 I don't know.  whatever.
+	elif [ $ret -eq 2 ]; then
+		log_failure_msg "Munin-Node is dead, although $PIDFILE exists."
+		exit 1
+	elif [ $ret -eq 3 ]; then
+		log_warning_msg "Munin-Node is not running."
+		exit 3
+	fi
+	log_warning_msg "Munin-Node status unknown."
+	exit 4
+        ;;
   *)
-	N=/etc/init.d/$NAME
-	echo "Usage: $N {start|stop|restart|force-reload}" >&2
-	exit 1
+	log_failure_msg "Usage: /etc/init.d/munin-node" \
+			"{start|stop|restart|force-reload|try-restart}"
+	exit 2
 	;;
 esac
 
-exit 0
+log_failure_msg "Unexpected failure, please file a bug."
+exit 1
