munin-check: use proper bash syntax

diff --git a/master/_bin/munin-check.in b/master/_bin/munin-check.in
--- a/master/_bin/munin-check.in
+++ b/master/_bin/munin-check.in
@@ -21,7 +21,7 @@
 ####
 # prints usage
 function usage() {
-echo "Usage: munin-check [options]
+    echo "Usage: munin-check [options]
 Options:
    -h|--help		Show this help.
    -f|--fix-permissions Fix the permissions of the munin dirs and files.
@@ -30,29 +30,27 @@ Options:
 Please don't use this script if you are using 'graph_strategy cgi'!
 It doesn't care about the right permissions for www-data yet...
 "
-
-
 }
 
 # Get options from the command line
-TEMP=`getopt -o fh --long fix-permissions,help \
-     -n 'munin-check' -- "$@"`
+TEMP=$(getopt -o fh --long fix-permissions,help -n 'munin-check' -- "$@")
 
-if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+if [[ $? -ne 0 ]]; then
+    echo "Terminating..." >&2
+    exit 1
+fi
 
 # Note the quotes around `$TEMP': they are essential!
 eval set -- "$TEMP"
 
-while true ; do
-	case "$1" in
-		-h|--help) usage ; exit 0; shift ;;
-		-f|--fix-permissions) PLEASE_FIXME="true" ;  shift ;;
-		--) shift ; break ;;
-		*) echo "Internal error!" ; exit 1 ;;
-	esac
+while :; do
+    case "$1" in
+	-h|--help) usage ; exit 0; shift ;;
+	-f|--fix-permissions) PLEASE_FIXME="true" ;  shift ;;
+	--) shift ; break ;;
+	*) echo "Internal error!" ; exit 1 ;;
+    esac
 done
-
-
 
 ####
 # sets owner to "@@USER@@"
@@ -60,7 +58,7 @@ function fix_owner() {
     fix_object=$1; shift
     fix_owner=$1; shift
 
-    if [ "$(id -u)" = "0" ]; then
+    if [[ $(id -u) -eq 0 ]]; then
 	# -R is wrong, in case we're not recursing, and if we are
 	# recursing then fix_owner will be called again.  OK, that's
 	# slower, but still more correct.
@@ -74,20 +72,20 @@ function fix_owner() {
 ####
 # check if "@@USER@@" is owner, if PLEASE_FIXME set it calls fix_owner()
 
-function owner_ok(){
+function owner_ok() {
     object=$1; shift || exit 1
     correctowner=$1; shift || exit 1
 
     owner=$(stat -c%U $object)
-    if [ "$owner" != "$correctowner" ]; then
+    if [[ "$owner" != "$correctowner" ]]; then
 	echo "# $object : Wrong owner ($owner != $correctowner)";
-	if [ "$PLEASE_FIXME" = "true" ]; then
+	if [[ "$PLEASE_FIXME" == "true" ]]; then
 	    fix_owner $object $correctowner
 	fi
     fi
 
-    if [ -d $object ]; then
-	if [ -n "$norec" ]; then
+    if [[ -d $object ]]; then
+	if [[ -n "$norec" ]]; then
 	    # The $norec variable cuts off recursion
 	    return 0
 	fi
@@ -109,17 +107,17 @@ function perm_ok(){
     correctperm=$1; shift || exit 1
 
     perm=$(stat -c%a $object)
-    if [ "$perm" != "$correctperm" ]; then
+    if [[ $perm -ne $correctperm ]]; then
 	echo "# $object : Wrong permissions ($perm != $correctperm)";
-	if [ "$PLEASE_FIXME" = "true" ]; then
+	if [[ "$PLEASE_FIXME" == "true" ]]; then
 	    chmod $correctperm $object
 	fi
     fi
 
-    if [ -d $object ]; then
+    if [[ -d $object ]]; then
 	# check the owner of the dir ...
 
-	if [ -n "$norec" ]; then
+	if [[ -n "$norec" ]]; then
 	    # The $norec variable cuts off recursion
 	    return 0
 	fi
@@ -157,10 +155,9 @@ norec=yes owner_ok @@LOGDIR@@ @@USER@@
 norec=yes owner_ok @@DBDIR@@ @@USER@@
 norec=yes perm_ok @@DBDIR@@ 755
 
-for dir in @@DBDIR@@/datafile @@DBDIR@@/limits \
-    @@DBDIR@@/*.stats; do
-	norec=yes owner_ok $dir @@USER@@
-	norec=yes perm_ok $dir 644
+for dir in @@DBDIR@@/datafile @@DBDIR@@/limits @@DBDIR@@/*.stats; do
+    norec=yes owner_ok $dir @@USER@@
+    norec=yes perm_ok $dir 644
 done
 
 norec=yes owner_ok @@PLUGSTATE@@ @@PLUGINUSER@@
