Plugin digitemp_: fix shellcheck issues; clarify error message

diff --git a/plugins/node.d/digitemp_.in b/plugins/node.d/digitemp_.in
--- a/plugins/node.d/digitemp_.in
+++ b/plugins/node.d/digitemp_.in
@@ -45,12 +45,12 @@ with this program; if not, write to the Free Software Foundation, Inc.,
 =cut
 
 # common values: digitemp_DS2490, digitemp_DS9097, digitemp_DS9097U
-digitemp=${0##*/}
-model=${digitemp##*_}
+digitemp_bin=${0##*/}
+model=${digitemp_bin##*_}
 digitemprc=${digitemprc:-/etc/digitemp.conf}
 
-if ! [ -x "$(which "$digitemp")" ]; then
-    echo "$digitemp not found" >&2
+if ! [ -x "$(which "$digitemp_bin")" ]; then
+    echo "executable '$digitemp_bin' not found" >&2
     exit 1
 fi
 
@@ -59,7 +59,7 @@ if [ "$1" = "config" ]; then
     echo 'graph_vlabel degrees C'
     echo 'graph_category sensors'
     echo "graph_info This graph shows the temperature read from $model 1-wire sensors"
-    $digitemp -c "$digitemprc" -q -a -o '%s %R' | grep -v ^Found | while read -r sensor serial; do
+    "$digitemp_bin" -c "$digitemprc" -q -a -o '%s %R' | grep -v ^Found | while read -r sensor serial; do
         echo "sensor$serial.label sensor #$sensor"
         echo "sensor$serial.type GAUGE"
         echo "sensor$serial.info Temperature from sensor #$sensor"
@@ -69,4 +69,4 @@ if [ "$1" = "config" ]; then
    exit 0
 fi
 
-$digitemp -c "$digitemprc" -q -a -o 'sensor%R.value %C'|grep -v ^Found
+"$digitemp_bin" -c "$digitemprc" -q -a -o 'sensor%R.value %C'|grep -v ^Found
