Signal error in http_loadtime
(cherry picked from commit 9511ed62b9c0780b4f365d30f586a0a5c9c459c3)

diff --git a/plugins/node.d/http_loadtime.in b/plugins/node.d/http_loadtime.in
--- a/plugins/node.d/http_loadtime.in
+++ b/plugins/node.d/http_loadtime.in
@@ -103,9 +103,13 @@ cd $TEMPO_DIR || exit 1
 for uri in $urls
 do
     loadtime=`$time_bin -f "%e" wget $wget_opt --header='Accept-Encoding: gzip,deflate' $uri 2>&1`
-
-    esc_uri="$(clean_fieldname "$uri")"
-    echo $esc_uri".value $loadtime"
+    if [ "$?" != "0" ]; then
+        esc_uri="$(clean_fieldname "$uri")"
+        echo $esc_uri".value $loadtime"
+    else
+        echo "Download error during $uri" 1>&2
+        exit 1
+    fi
 done
 
 exit 0
