Fix 1350, user agent, auto config

diff --git a/plugins/node.d/http_loadtime b/plugins/node.d/http_loadtime
--- a/plugins/node.d/http_loadtime
+++ b/plugins/node.d/http_loadtime
@@ -1,23 +1,17 @@
-#!/bin/bash
+#!@@BASH@@
+# -*- sh -*-
 
 : << =cut
 
 =head1 NAME
 
-http_loadtime - Plugin to graph the HTTP response times of specific pages
+http_loadtime - Plugin to graph HTTP response time of a specific page
 
 =head1 CONFIGURATION
 
 The following environment variables are used by this plugin
 
- target - comma separated URL(s) to fetch (default: "http://localhost/")
- example:
-   [http_loadtime]
-   env.target http://localhost.de,http://localhost.de/some-site.html
-   env.requisites true
-
- Do not enable the download of page requisites (env.requisites) for https
- sites since wget needs incredible long to perform this on big sites...
+ target - URL to fetch (default: "http://localhost/")
 
 =head1 AUTHOR
 
@@ -35,17 +29,8 @@ GPLv2
 
 =cut
 
-. $MUNIN_LIBDIR/plugins/plugin.sh
-
 target=${target:-"http://localhost/"}
-requisites=${requisites:-"false"}
-
-urls=`echo $target | tr "," "\n"`
-wget_opt="--user-agent munin/http_loadtime --no-cache -q"
-if [ "$requisites" == "true" ]; then
-  wget_opt="$wget_opt --page-requisites"
-fi
-
+wget_opt="--user-agent \"Munin - http_loadtime\" --no-cache -q"
 time_bin=`which time`
 
 if [ "$1" = "autoconf" ]; then
@@ -54,23 +39,16 @@ if [ "$1" = "autoconf" ]; then
     command -v tr        2>&1 >/dev/null || result=1
     command -v wget      2>&1 >/dev/null || result=1
     if [ "$result" != "yes" ]; then
-	echo "no (programs time, wget and tr required)"
-	exit 0
+    	echo "no (programs time, wget and tr required)"
+	    exit 0
     fi
 
-    # if $target contains more than one url
-    if ! wget -q -O /dev/null $target; then
-
-        # check if urls respond
-        #
-        for uri in $urls
-        do
-            wget --spider $uri $wget_opt
-            if [ "$?" != "0" ]; then
-                echo "no (Cannot run wget against \"$uri\")"
-                exit 0
-            fi
-        done
+    # check if url responds
+    #
+    wget --spider $target $wget_opt
+    if [ "$?" != "0" ]; then
+        echo "no (Cannot run wget against \"$target\")"
+        exit 0
     fi
     echo yes
     exit 0
@@ -81,15 +59,9 @@ if [ "$1" = "config" ]; then
     echo "graph_args --base 1000 -l 0"
     echo "graph_vlabel Load time in seconds"
     echo "graph_category network"
-    echo "graph_info This graph shows the load time in seconds"
-    for uri in $urls
-    do
-        uri_short=`echo ${uri:0:30}`
-        if [ "$uri_short" != "$uri" ]; then uri_short=$uri_short"..."; fi
-        esc_uri="$(clean_fieldname "$uri")"
-        echo $esc_uri".label $uri_short"
-        echo $esc_uri".info page load time"
-    done
+    echo "graph_info This graph shows load time in seconds of $target"
+    echo "loadtime.label loadtime"
+    echo "loadtime.info Load time"
     exit 0
 fi
 
@@ -98,17 +70,7 @@ TEMPO_DIR=$(mktemp -dt munin_http_loadtime.XXXXXX) || exit 1
 trap "rm -rf $TEMPO_DIR" EXIT
 
 cd $TEMPO_DIR || exit 1
+loadtime=`$time_bin --quiet -f "%e" wget $wget_opt $target 2>&1`
+cd -
 
-for uri in $urls
-do
-    loadtime=`$time_bin -f "%e" wget $wget_opt --header='Accept-Encoding: gzip,deflate' $uri 2>&1`
-    if [ "$?" == "0" ]; then
-        esc_uri="$(clean_fieldname "$uri")"
-        echo $esc_uri".value $loadtime"
-    else
-        echo "Download error during $uri" 1>&2
-        exit 1
-    fi
-done
-
-exit 0
+echo "loadtime.value $loadtime"
