Plugins jenkins_*: shellcheck issues and update interval handling
* fix all shellcheck issues
* add default value and documentation for "jenkins_update_interval"

diff --git a/plugins/node.d/jenkins_builds_results_summary b/plugins/node.d/jenkins_builds_results_summary
--- a/plugins/node.d/jenkins_builds_results_summary
+++ b/plugins/node.d/jenkins_builds_results_summary
@@ -6,6 +6,15 @@
 
 jenkins_builds_results_summary - Plugin to measure results of all jenkins builds
 
+=head1 CONFIGURATION
+
+[jenkins_builds]
+env.jenkins_update_interval 15
+
+jenkins_update_interval: minimum number of minutes between successive
+    update operations (adjust according to your resource limits)
+    Default: 15
+
 =head1 AUTHOR
 
 Contributed by Holger Levsen. I wrote and used them first for
@@ -30,9 +39,12 @@ Released under the GPLv2.
 
 =cut
 
-. $MUNIN_LIBDIR/plugins/plugin.sh
+# shellcheck disable=SC1090
+. "$MUNIN_LIBDIR/plugins/plugin.sh"
 
-if [ "$1" = "autoconf" ]; then
+jenkins_update_interval=${jenkins_update_interval:-15}
+
+if [ "${1:-}" = "autoconf" ]; then
 	if [ -d /var/lib/jenkins/jobs ]; then
 		echo yes
 	else
@@ -41,42 +53,38 @@ if [ "$1" = "autoconf" ]; then
 	exit 0
 fi
 
-STATEFILE=$MUNIN_PLUGSTATE/$(basename $0)
+STATEFILE=$MUNIN_PLUGSTATE/$(basename "$0")
 
 # delete statefile if it's older than ${jenkins_update_interval} set in /etc/munin/plugin-conf.d/jenkins
-if test $(find $STATEFILE -mmin +${jenkins_update_interval}) ; then
-	rm -f $STATEFILE
-fi
+find "$STATEFILE" -maxdepth 0 -mmin "+$jenkins_update_interval" -delete 2>&1 || true
 
-if [ -f $STATEFILE ] && [ "$1" = "" ] ; then
-	cat $STATEFILE
+if [ -f "$STATEFILE" ] && [ -z "${1:-}" ] ; then
+	cat "$STATEFILE"
 	exit 0
 fi
 
-if [ "$1" = "config" ]; then
+if [ "${1:-}" = "config" ]; then
 	echo 'graph_title Jenkins Builds results summary'
 	echo 'graph_args --base 1000 -l 0 '
 	echo 'graph_scale no'
 	echo 'graph_total total'
 	echo 'graph_vlabel Jenkins Builds results summary'
 	echo 'graph_category devel'
-	draw=AREA
 	for STATE in success unstable failure ; do
 		echo "jenkins_builds_results_all_${STATE}.label ${PREFIX} ${STATE}"
-		echo "jenkins_builds_results_all_${STATE}.draw $draw"
-		if [ "$draw" = "AREA" ] ; then draw=STACK ; fi
+		echo "jenkins_builds_results_all_${STATE}.draw AREASTACK"
 	done
 	exit 0
 fi
 
-RESULTS=$(for i in /var/lib/jenkins/jobs/*/builds/*_*/log ; do tail -1 $i 2>/dev/null; echo " \n"; done )
+RESULTS=$(for i in /var/lib/jenkins/jobs/*/builds/*_*/log; do tail -1 "$i" 2>/dev/null; echo; done)
 for STATE in success unstable failure ; do
 	NR=0
 	if [ "$STATE" = "failure" ] ; then
 		# count aborted as failed
-		NR=$(echo -e "$RESULTS" | egrep -i -c "($STATE|aborted)")
+		NR=$(echo -e "$RESULTS" | grep -E -i -c "($STATE|aborted)")
 	else
-		NR=$(echo -e "$RESULTS" | grep -i -c $STATE)
+		NR=$(echo -e "$RESULTS" | grep -i -c "$STATE")
 	fi
-	echo "jenkins_builds_results_all_${STATE}.value $NR" | tee -a $STATEFILE
+	echo "jenkins_builds_results_all_${STATE}.value $NR" | tee -a "$STATEFILE"
 done
