processes plugin - implement autoconf

diff --git a/plugins/node.d/processes.in b/plugins/node.d/processes.in
--- a/plugins/node.d/processes.in
+++ b/plugins/node.d/processes.in
@@ -67,11 +67,31 @@ munin-node.
 [ $ps ]      || ps="ps"
 
 # Find operating system
-[ $OPERSYS ] || OPERSYS=`uname` || exit 1
+[ $OPERSYS ] || OPERSYS=`uname | cut -f 1 -d _` || exit 1
 
 if [ "$1" = "autoconf" ]; then
+        case "$OPERSYS" in
+        Linux|SunOS|FreeBSD|OpenBSD|NetBSD|Darwin)
+        $ps >/dev/null 2>/dev/null
+        if [ $? -ne 0 ]
+        then
+            echo "no (ps=$ps failed)"
+            exit 0
+        fi
+        echo | $awk '{ print "Hei" }' >/dev/null 2>/dev/null
+        if [ $? -ne 0 ]
+        then
+            echo "no (awk=$awk failed)"
+            exit 0
+        fi
 	echo yes
 	exit 0
+	;;
+	*)
+	echo "no (unknown OS)"
+	exit 0
+	;;
+	esac
 fi
 
 . $MUNIN_LIBDIR/plugins/plugin.sh
