update munin maintscripts
- remove apache config on upgrade

- remove /var/spool/munin /var/lib/munin /var/cache/munin and
  /var/log/munin on purge

diff --git a/debian/munin.postrm b/debian/munin.postrm
--- a/debian/munin.postrm
+++ b/debian/munin.postrm
@@ -1,61 +1,49 @@
-#! /bin/sh
+#!/bin/sh
+# postrm script for munin
+#
+# see: dh_installdeb(1)
 
 set -e
 
-# workaround for bug #198522
-delete_dir_if_empty() {
-	if [ ! -d "$1" ]; then
-		return 0;
-	fi
-	rmdir --ignore-fail-on-non-empty $1;
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+purge_dirs() {
+    rm -rf /var/cache/munin
+    rm -rf /var/spool/munin
+    rm -rf /var/lib/munin
+    rm -rf /var/log/munin
 }
 
+case "$1" in
+    purge)
+        purge_dirs
+    ;;
+    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+    ;;
 
-if [ "$1" = "purge" ]; then
+    *)
+        echo "postrm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
 
-	echo "The generated web site or accumulated data won't be removed."
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
-	rm -f /var/lib/munin/datafile
-	rm -f /var/lib/munin/limits
-	rm -f /var/lib/munin/*.stats
-	rm -f /var/lib/munin/*/*.ok
-
-	rm -f /var/log/munin/munin-update.log*
-	rm -f /var/log/munin/munin-limits.log*
-
-	delete_dir_if_empty /var/cache/munin/www
-	delete_dir_if_empty /var/lib/munin/cgi-tmp
-	delete_dir_if_empty /var/lib/munin
-	delete_dir_if_empty /var/log/munin
-	delete_dir_if_empty /etc/munin/templates
-	delete_dir_if_empty /etc/munin
-
-        if [ -d /var/spool/munin ]; then
-                find /var/spool/munin -delete
-	fi
-
-	webserver=apache2
-	if [ -L /etc/$webserver/conf.d/munin ]; then
-		# delete the link
-		rm -f /etc/$webserver/conf.d/munin
-		# apache2-maintscript-helper will restart apache anyway
-		if [ ! -e /usr/share/apache2/apache2-maintscript-helper ] ; then
-			invoke-rc.d $webserver reload 3>/dev/null || true
-		fi
-	fi
-	
-	# Disable configuration with Apache 2.4
-	if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
-		. /usr/share/apache2/apache2-maintscript-helper 
-		apache2_invoke disconf munin.conf 
-	fi 
-	
-	# Remove configuration from Apache 2.4 conf dir
-	if [ -L /etc/$webserver/conf-available/munin.conf ]; then
-		# delete the link
-		rm -f /etc/$webserver/conf-available/munin.conf
-	fi
-fi
-
+dpkg-maintscripts-helper rm_conffile /etc/munin/apache.conf 2.999.1-1~ -- "$@"
+dpkg-maintscripts-helper rm_conffile /etc/munin/apache24.conf 2.999.1-1~ -- "$@"
 
 #DEBHELPER#
+
+exit 0
