munin-check: unify whitespace
converted mixed tab/space indentation to space-only indentation

diff --git a/script/munin-check b/script/munin-check
--- a/script/munin-check
+++ b/script/munin-check
@@ -21,10 +21,10 @@
 function usage() {
     echo "Usage: munin-check [options]
 Options:
-   -h|--help		Show this help.
-   -v|--verbose		Be verbose.
-   -f|--fix-permissions Fix the permissions of the munin dirs and files.
-   			Needs superuser rights.
+   -h|--help             Show this help.
+   -v|--verbose          Be verbose.
+   -f|--fix-permissions  Fix the permissions of the munin dirs and files.
+                         Needs superuser rights.
 
 Please don't use this script if you are using 'graph_strategy cgi'!
 It doesn't care about the right permissions for www-data yet...
@@ -47,11 +47,11 @@ PLEASE_FIXME="false"
 VERBOSE="false"
 while :; do
     case "$1" in
-	-h|--help) usage ; exit 0; shift ;;
-	-v|--verbose) VERBOSE="true"; shift;;
-	-f|--fix-permissions) PLEASE_FIXME="true" ;  shift ;;
-	--) shift ; break ;;
-	*) echo "Internal error!" ; exit 1 ;;
+        -h|--help) usage ; exit 0; shift ;;
+        -v|--verbose) VERBOSE="true"; shift;;
+        -f|--fix-permissions) PLEASE_FIXME="true" ;  shift ;;
+        --) shift ; break ;;
+        *) echo "Internal error!" ; exit 1 ;;
     esac
 done
 
@@ -71,14 +71,14 @@ function fix_owner() {
     fix_owner=$1; shift
 
     if [[ $(id -u) -eq 0 ]]; then
-        msg_info "# $fix_object : Fixing owner ($fix_owner)";
-	# -R is wrong, in case we're not recursing, and if we are
-	# recursing then fix_owner will be called again.  OK, that's
-	# slower, but still more correct.
-	chown "$fix_owner" "$fix_object"
+        msg_info "# $fix_object : Fixing owner ($fix_owner)"
+        # -R is wrong, in case we're not recursing, and if we are
+        # recursing then fix_owner will be called again.  OK, that's
+        # slower, but still more correct.
+        chown "$fix_owner" "$fix_object"
     else
-	echo "Fixing the permissions needs superuser rights. You should run \"munin-check -f\" as root."
-	exit 0
+        echo "Fixing the permissions needs superuser rights. You should run \"munin-check -f\" as root."
+        exit 0
     fi
 }
 
@@ -91,26 +91,26 @@ function owner_ok() {
 
     owner=$(stat --format %U "$object")
     if [[ "$owner" != "$correctowner" ]]; then
-	echo "# $object : Wrong owner ($owner != $correctowner)";
-	if [[ "$PLEASE_FIXME" == "true" ]]; then
-	    fix_owner "$object" "$correctowner"
-	fi
+        echo "# $object : Wrong owner ($owner != $correctowner)"
+        if [[ "$PLEASE_FIXME" == "true" ]]; then
+            fix_owner "$object" "$correctowner"
+        fi
     fi
 
     if [[ -d $object ]]; then
-	if [[ -n "$norec" ]]; then
-	    # The $norec variable cuts off recursion
-	    return 0
-	fi
+        if [[ -n "$norec" ]]; then
+            # The $norec variable cuts off recursion
+            return 0
+        fi
 
-	case $object in
-	    "lost+found") return 0;;
-	esac
+        case $object in
+            "lost+found") return 0;;
+        esac
 
-	# ... and then dive into it
-	for subobject in "$object"/*; do
-		owner_ok "$subobject" "$correctowner"
-	done
+        # ... and then dive into it
+        for subobject in "$object"/*; do
+            owner_ok "$subobject" "$correctowner"
+        done
     fi
 }
 
@@ -121,29 +121,29 @@ function perm_ok(){
 
     perm=$(perl -e 'printf "%o\n", 07777 & (stat $ARGV[0])[2]' "$object")
     if [[ $perm -ne $correctperm ]]; then
-	echo "# $object : Wrong permissions ($perm != $correctperm)";
-	if [[ "$PLEASE_FIXME" == "true" ]]; then
-            msg_info "# $object : Fixing permission ($correctperm)";
-	    chmod "$correctperm" "$object"
-	fi
+        echo "# $object : Wrong permissions ($perm != $correctperm)"
+        if [[ "$PLEASE_FIXME" == "true" ]]; then
+            msg_info "# $object : Fixing permission ($correctperm)"
+            chmod "$correctperm" "$object"
+        fi
     fi
 
     if [[ -d $object ]]; then
-	# check the owner of the dir ...
+        # check the owner of the dir ...
 
-	if [[ -n "$norec" ]]; then
-	    # The $norec variable cuts off recursion
-	    return 0
-	fi
+        if [[ -n "$norec" ]]; then
+            # The $norec variable cuts off recursion
+            return 0
+        fi
 
-	case $object in
-	    "lost+found") return 0;;
-	esac
+        case $object in
+            "lost+found") return 0;;
+        esac
 
-	# ... and then dive into it
-	for subobject in "$object"/*; do
-	    perm_ok "$subobject" "$correctperm"
-	done
+        # ... and then dive into it
+        for subobject in "$object"/*; do
+            perm_ok "$subobject" "$correctperm"
+        done
     fi
 }
 
@@ -159,8 +159,8 @@ owner_ok "@@HTMLDIR@@" "@@USER@@"
 for dir in "@@DBDIR@@"/*; do
     # Do not check the plugin-state directory
     case $dir in
-	*/plugin-state)
-	    continue;;
+        */plugin-state)
+            continue;;
     esac
     echo "check $dir"
     owner_ok "$dir" "@@USER@@"
